using System;

namespace Bsa.Hardware.Acquisition
{
    /// <summary>
    /// Represents the current mode of acquisition of a <see cref="AcquisitionDevice"/>.
    /// </summary>
    public enum AcquisitionMode
    {
        /// <summary>
        /// Device is disconnected or it is connected and configured but acquisition is paused.
        /// </summary>
        Idle,

        /// <summary>
        /// Device is connected and it is acquiring data.
        /// </summary>
        Data,

        /// <summary>
        /// Device is connected but it is <em>pushing out</em> calibration data.
        /// </summary>
        /// <remarks>
        /// Calibration data may be a true well-known signal injected into ADC or a synthetic signal generated by
        /// device or driver itself. This mode is optional, check for <see cref="AcquisitionDeviceFeatures.Calibration"/>.
        /// </remarks>
        Calibration,

        /// <summary>
        /// Device is connected but it is not producing data (or it is <em>pushing out</em> a reference value) because
        /// it is measuring inputs impedance.
        /// </summary>
        /// <remarks>
        /// This mode is optional, check for <see cref="AcquisitionDeviceFeatures.Ohmeter"/>.
        /// </remarks>
        Ohmeter,
    }
}
