//
// This file is part of Biological Signals Acquisition Framework (BSA-F).
// Copyright © Adriano Repetti 2016.
//
// BSA-F is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// BSA-F is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with BSA-F.  If not, see <http://www.gnu.org/licenses/>.
//

using System;

namespace Bsa.Hardware
{
    /// <summary>
    /// Specifies the class of an hardware error.
    /// </summary>
    public enum HardwareErrorClass
    {
        /// <summary>
        /// Error cause is unknown or it does not belong to any other class. Errors of this class
        /// may be temporary or permanent.
        /// </summary>
        Generic = 0,

        /// <summary>
        /// Error is caused by driver itself. Errors of this class are usually permanent.
        /// </summary>
        Internal = 1,

        /// <summary>
        /// Error is caused by an invalid configuration or invalid arguments. This class of errors should also be
        /// used when driver cannot access required information (for example because configuration is stored on an unaccessible
        /// device.) Errors of this class are permanent (unless configuration and/or arguments are corrected.)
        /// </summary>
        Arguments = 2,

        /// <summary>
        /// Error is caused by an invalid operation for the current device (or driver) state (for example a command
        /// cannot be executed if device is in a particular state). These errors are permanent unless another
        /// command (or device itself) forces a change in device state.
        /// </summary>
        State = 8,

        /// <summary>
        /// Error is caused by a request for an unsupported device/driver feature. Errors of this class
        /// are permanent.
        /// </summary>
        Unsupported = 9,

        /// <summary>
        /// Error is generated by device itself. It may be a device internal error, a faulty condition or an invalid
        /// command/sequence (in this case error is really a driver error). These errors are, unless issue was transitory,
        /// usually permanent and cannot be resolved without a technical operation on device itself.
        /// </summary>
        Device = 10,

        /// <summary>
        /// Error is caused by a communication error with the device. Errors of this class may be temporary
        /// (unless they're caused by a physical issue).
        /// </summary>
        Communication = 16,
    }
}
